export const data = JSON.parse("{\"key\":\"v-2aef503c\",\"path\":\"/%E5%B0%8F%E7%BE%8E%E6%96%87/thespringsong.html\",\"title\":\"卜算子·咏春\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"卜算子·咏春\",\"date\":\"2022-09-02T20:25:27.000Z\",\"author\":\"Mr.11.爱宠人\",\"isOriginal\":true,\"category\":[\"小美文\"],\"tag\":[\"美文\"],\"icon\":\"blog\",\"description\":\"卜算子•咏春【回文诗】 ｛早春篇｝ 凛凛寒风疾， 金桔映梅黄， 落叶松下雪皑皑， 滴水化冰棱。 疾风寒凛凛， 黄梅映桔金， 皑皑雪下松叶落， 棱冰化水滴。 ｛盛春篇｝ 泥润春风起， 风舞白花垂， 扬絮柳韵作飞花， 暖日虫始春。 起风春润泥， 垂花白舞风， 花飞作韵柳絮扬， 春始虫日暖。 ｛接夏篇｝ 早花嫌春晚， 鸣虫语花繁， 翠柳啼莺舞蝶忙， 飞霞恋西溪。 晚春嫌花早， 繁花语虫鸣， 忙蝶舞莺啼柳翠， 溪西恋霞飞。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.thomasxiao.com/%E5%B0%8F%E7%BE%8E%E6%96%87/thespringsong.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"oh-la!\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"卜算子·咏春\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"卜算子•咏春【回文诗】 ｛早春篇｝ 凛凛寒风疾， 金桔映梅黄， 落叶松下雪皑皑， 滴水化冰棱。 疾风寒凛凛， 黄梅映桔金， 皑皑雪下松叶落， 棱冰化水滴。 ｛盛春篇｝ 泥润春风起， 风舞白花垂， 扬絮柳韵作飞花， 暖日虫始春。 起风春润泥， 垂花白舞风， 花飞作韵柳絮扬， 春始虫日暖。 ｛接夏篇｝ 早花嫌春晚， 鸣虫语花繁， 翠柳啼莺舞蝶忙， 飞霞恋西溪。 晚春嫌花早， 繁花语虫鸣， 忙蝶舞莺啼柳翠， 溪西恋霞飞。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://www.thomasxiao.com/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"卜算子·咏春\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.11.爱宠人\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"美文\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-09-02T20:25:27.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"卜算子·咏春\\\",\\\"image\\\":[\\\"https://www.thomasxiao.com/\\\"],\\\"datePublished\\\":\\\"2022-09-02T20:25:27.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.11.爱宠人\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.61,\"words\":184},\"filePathRelative\":\"小美文/thespringsong.md\",\"localizedDate\":\"2022年9月3日\",\"excerpt\":\"<p></p>\\n<p>卜算子•咏春【回文诗】</p>\\n<p>｛早春篇｝\\n凛凛寒风疾，\\n金桔映梅黄，\\n落叶松下雪皑皑，\\n滴水化冰棱。</p>\\n<p>疾风寒凛凛，\\n黄梅映桔金，\\n皑皑雪下松叶落，\\n棱冰化水滴。</p>\\n<p>｛盛春篇｝\\n泥润春风起，\\n风舞白花垂，\\n扬絮柳韵作飞花，\\n暖日虫始春。</p>\\n<p>起风春润泥，\\n垂花白舞风，\\n花飞作韵柳絮扬，\\n春始虫日暖。</p>\\n<p>｛接夏篇｝\\n早花嫌春晚，\\n鸣虫语花繁，\\n翠柳啼莺舞蝶忙，\\n飞霞恋西溪。</p>\\n<p>晚春嫌花早，\\n繁花语虫鸣，\\n忙蝶舞莺啼柳翠，\\n溪西恋霞飞。</p>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
