export const themeData = JSON.parse("{\"blog\":{\"name\":\"Mr.爱宠人\",\"description\":\"hi,大家好！我是个狗狗爱好者，平时喜欢看书和看电影，也喜欢羽毛球；最讨厌有人在公共场合大声“狗叫”。\",\"intro\":\"/aboutme.md\",\"medias\":{\"Baidu\":\"https://example.com\",\"Dingding\":\"https://example.com\",\"Email\":\"https://example.com\",\"Gitee\":\"https://example.com\",\"GitHub\":\"https://github.com/Ohlalala1021\",\"Gitlab\":\"https://example.com\",\"Gmail\":\"https://example.com\",\"Wechat\":\"https://example.com\",\"Youtube\":\"https://example.com\",\"Zhihu\":\"https://example.com\"}},\"encrypt\":{\"config\":{\"/%E5%B0%8F%E9%9A%8F%E7%AC%94/\":[\"$2a$10$u35F9zQCk.oAIWi5R8hUoeSYMf3lxkVkL9sVyFXeGErLVbyiiLWxm\"],\"/%E5%B0%8F%E7%AC%94%E8%AE%B0/\":[\"$2a$10$TovYPI/sEDi1xpeggxQlJu.Bs3KY.wd5JSht4FuTHjfGOEnC1M5tK\"]}},\"pure\":false,\"darkmode\":\"switch\",\"themeColor\":false,\"fullscreen\":false,\"locales\":{\"/\":{\"blog\":{},\"repoDisplay\":true,\"navbarIcon\":true,\"navbarAutoHide\":\"mobile\",\"hideSiteNameonMobile\":true,\"sidebar\":{},\"sidebarIcon\":true,\"headerDepth\":2,\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"编辑此页\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"收藏\",\"slides\":\"幻灯片\",\"encrypt\":\"加密\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"iconLabel\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"404msg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"author\":{\"name\":\"Mr.11.爱宠人\",\"url\":\"https://mrhope.site\"},\"logo\":\"/logo.jpeg\",\"repo\":\"Ohlalala1021/Ohlalala1021.github.io\",\"docsDir\":\"demo/src\",\"navbar\":[\"/\",\"/home\",{\"text\":\"使命必达\",\"link\":\"/小目标/5thgradeterm1\"},{\"text\":\"书写美好\",\"icon\":\"creative\",\"link\":\"/小美文/cookiemydog\"},{\"text\":\"学而时习之\",\"icon\":\"edit\",\"link\":\"/小导图/thedynastyandtrustofthepeople\"},{\"text\":\"lala\",\"icon\":\"edit\",\"prefix\":\"article/\",\"children\":[{\"text\":\"学而时习之\",\"icon\":\"edit\",\"link\":\"/小导图/thedynastyandtrustofthepeople\"}]}],\"footer\":\"默认页脚\",\"displayFooter\":true,\"pageInfo\":[\"Author\",\"Original\",\"Date\",\"Category\",\"Tag\",\"ReadingTime\"]}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
