export const data = JSON.parse("{\"key\":\"v-7e95f752\",\"path\":\"/%E5%B0%8F%E9%9A%8F%E7%AC%94/2022-10/10-2.html\",\"title\":\"泥巴节\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"泥巴节\",\"date\":\"2022-10-02T22:28:45.000Z\",\"author\":\"Mr.11.爱宠人\",\"isOriginal\":true,\"category\":[\"小随笔\"],\"tag\":[\"随笔\"],\"icon\":\"blog\",\"description\":\"10.2 image-20221002224905895 今天绝对是个值得纪念的“大型混乱现场”，事情是这样的…… 我和朱，羊，魏，颜，王，曹一起捉螃蟹🦀️。在归来时，不知是哪个究极无敌终极超级mega极巨化的大混球在我脑袋上放了一个泥球，把我坑的够跄。等到我找到那个人——小魏魏，我开始疯狂拿泥球反攻。他跑了。我以为没事了的时候，突然四个泥球砸在了我...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.thomasxiao.com/%E5%B0%8F%E9%9A%8F%E7%AC%94/2022-10/10-2.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"oh-la!\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"泥巴节\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"10.2 image-20221002224905895 今天绝对是个值得纪念的“大型混乱现场”，事情是这样的…… 我和朱，羊，魏，颜，王，曹一起捉螃蟹🦀️。在归来时，不知是哪个究极无敌终极超级mega极巨化的大混球在我脑袋上放了一个泥球，把我坑的够跄。等到我找到那个人——小魏魏，我开始疯狂拿泥球反攻。他跑了。我以为没事了的时候，突然四个泥球砸在了我...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://www.thomasxiao.com/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"泥巴节\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.11.爱宠人\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"随笔\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-10-02T22:28:45.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"泥巴节\\\",\\\"image\\\":[\\\"https://www.thomasxiao.com/\\\"],\\\"datePublished\\\":\\\"2022-10-02T22:28:45.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.11.爱宠人\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.66,\"words\":198},\"filePathRelative\":\"小随笔/2022-10/10-2.md\",\"localizedDate\":\"2022年10月3日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
