export const data = JSON.parse("{\"key\":\"v-151da8c2\",\"path\":\"/%E5%B0%8F%E9%9A%8F%E7%AC%94/2022-9/9-1.html\",\"title\":\"小助教\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"小助教\",\"date\":\"2022-09-02T20:24:07.000Z\",\"author\":\"Mr.11.爱宠人\",\"isOriginal\":true,\"category\":[\"小随笔\"],\"tag\":[\"随笔\"],\"icon\":\"blog\",\"description\":\"image-20220906195814711 9.1 今天课间打了这个学期第一场躲避飞盘，我竟然接住了林子迪的球！可惜被曾曾补了一刀😭😭😭。中午，朱老师让我教同学们打羽毛球？！我又惊又喜，暗暗下了觉心：一定要教好同学们！同时，我还想请李子澄来当我的小助教。一来她打的好，帮帮忙没啥问题；二来，也发展下感情😁😁😁\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.thomasxiao.com/%E5%B0%8F%E9%9A%8F%E7%AC%94/2022-9/9-1.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"oh-la!\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"小助教\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"image-20220906195814711 9.1 今天课间打了这个学期第一场躲避飞盘，我竟然接住了林子迪的球！可惜被曾曾补了一刀😭😭😭。中午，朱老师让我教同学们打羽毛球？！我又惊又喜，暗暗下了觉心：一定要教好同学们！同时，我还想请李子澄来当我的小助教。一来她打的好，帮帮忙没啥问题；二来，也发展下感情😁😁😁\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://www.thomasxiao.com/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"小助教\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.11.爱宠人\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"随笔\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-09-02T20:24:07.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"小助教\\\",\\\"image\\\":[\\\"https://www.thomasxiao.com/\\\"],\\\"datePublished\\\":\\\"2022-09-02T20:24:07.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.11.爱宠人\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.48,\"words\":143},\"filePathRelative\":\"小随笔/2022-9/9-1.md\",\"localizedDate\":\"2022年9月3日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
